### PR TITLE
iCub with hands and cameras model

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
@traversaro please check this and let me know silvio.

### CODE REVIEW

**Comment by traversaro** [comment]
@Yeshasvitvs I think it is better if you just do the necessary modifications to the `icub_with_hands` model and then you remove `icub_with_cameras` , @randaz81 has recently worked on it and copy-pasting that SDF model will complicate mantainance (eventually everything would need to be automatically generated from  https://github.com/robotology-playground/icub-model-generator, but we are still a bit far).

**Comment by Yeshasvitvs** [comment]
Yes I understand. I was also wondering why camera conf are not included inside the icub model 

Cheers

**Comment by traversaro** [comment]
`icub` is the original model, used by a lot of demos and experiments. I think it is safer to rename it to `icub_without_hands_and_cameras` and leave it like that, and point new "general" users to the "complete" model. See https://github.com/robotology/icub-gazebo/issues/39 for a general discussion.

**Comment by Yeshasvitvs** [comment]
thanks for the update. I will close the PR

**Pull request closed without merging**
