### PR TITLE
Fix wrong minimum joint limits for iCub fingers

### PR DESCRIPTION
**Pull request by xEnVrE**
This PR fixes wrong minimum joint limits for joints belonging to the iCub hand.

### CODE REVIEW

**Comment by xEnVrE** [comment]
cc @kouroshD

**Comment by traversaro** [comment]
Just to understand, how is this related to https://github.com/robotology/gazebo-yarp-plugins/pull/472 ? Is that PR required for this change, or they are not related?

**Comment by traversaro** [comment]
Hi @xEnVrE, there is any reference for these limits or they are based on the experience of some specific iCub model? In any case, can you please target the branch `devel` ? Even if this is a fix, it changes a lot the limits, so I think it is safe to first merge in the `devel` branch, thanks. In any case, it will be merged in master released in may with the release of icub-gazebo 1.16.

**Comment by xEnVrE** [comment]
>  there is any reference for these limits or they are based on the experience of some specific iCub model

Hi @traversaro, I think I can be quite sure about these limits as, typically, on iCub robots, when fingers are completely open the encoders reads, ideally, `0.0`. Letting the minimum limits to be negative means that we are allowing the fingers joints to assume configurations that are not possible on the real robot.

**Comment by xEnVrE** [comment]
> I think it is safe to first merge in the devel branch, thanks. In any case, it will be merged in master released in may with the release of icub-gazebo 1.16

Sure!

**Comment by xEnVrE** [comment]
> Just to understand, how is this related to robotology/gazebo-yarp-plugins#472 ? Is that PR required for this change, or they are not related?

They are kind of related as both PR deals with limits. However, even without PR robotology/gazebo-yarp-plugins#472, these limits are wrong because those configurations are not possible on the real robots. Hence, this PR does not need  robotology/gazebo-yarp-plugins#472.

**Comment by xEnVrE** [comment]
Now the PR is on top of current `devel`.

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
